### ISSUE TITLE
Crash when opening Full PDF Viewer in Example Project

### ISSUE THREAD

**Issue by kfindfly** [uxmstudio/UXMPDFKit#42] opened 2017-02-17 07:16 UTC
Hi! I've just build and run your Example Program with Xcode 8.0. It's OK for the first time after I click 'Show Full PDF Viewer', but the program crashed in a second when I back to ExampleViewController and click it again. The problem wasn't gone until I deleted the program in Simulator. And the problem comes again after I run the Example and click 'Show Full PDF Viewer'. Can you help to have a look please?
Very thanks!

```
'annotations = aDecoder.decodeObject(forKey: "annotations") as! [PDFAnnotation]' in PDFAnnotationStore
```

**Comment by pushchris** [comment] 2017-02-17 16:19
@kfindfly please take a look at the latest build. I was not able to reproduce your issue, but I'm assuming that the bug is caused by the inference that the decoded objected will contain annotations. It has been changed to an optional parameter. If the issue is still present, please give me more details as to the problem.

**Comment by pushchris** [comment] 2017-03-07 17:34
Closing this issue, reopen if it is still present.

**Closed by pushchris** 2017-03-07 17:34 UTC
